apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web
  labels:
    app: node-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: node-web
        image: kvnikhill/nodeproject1:64
        ports:
        - containerPort: 3000
